import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

function source(path: string): string {
  return readFileSync(resolve(process.cwd(), path), 'utf8');
}

describe('desktop React plan points inspector', () => {
  it('shows changed files and plan in browser-style unlimited tabs', () => {
    const inspector = source('desktop/src/components/inspector/Inspector.tsx');
    const subagentDetail = source('desktop/src/components/inspector/SubagentDetailView.tsx');
    const app = source('desktop/src/App.tsx');
    const chatArea = source('desktop/src/components/chat/ChatArea.tsx');
    const composer = source('desktop/src/components/chat/Composer.tsx');
    const css = source('desktop/src/index.css');
    const points = source('desktop/src/components/inspector/PlanPoints.tsx');
    const taskRows = source('desktop/src/components/primitives/TaskRows.tsx');
    const reviewPanel = source('desktop/src/components/inspector/ReviewPanel.tsx');
    const reviewSidebar = source('desktop/src/components/inspector/ReviewSidebar.tsx');
    const reviewEmpty = source('desktop/src/components/inspector/ReviewEmpty.tsx');

    expect(inspector).toContain('data-plan-inspector');
    expect(inspector).toContain('bg-page');
    expect(inspector).not.toContain('border-l border-slate-200/80');
    expect(subagentDetail).toContain('bg-page');
    expect(chatArea).toContain('bg-page');
    expect(composer).toContain('from-[var(--page)]');
    expect(css).toContain('--focus: color-mix');
    expect(css).not.toContain('--surface-workspace');
    expect(app).toContain('data-sidebar-resizer=""');
    expect(app).toContain('data-inspector-resizer=""');
    expect(app.match(/bg-line-strong/g)?.length).toBeGreaterThanOrEqual(2);
    expect(app.match(/before:w-\[8px\]/g)?.length).toBe(2);
    expect(app).not.toContain('w-[4px] -ml-[2px]');
    expect(app).not.toContain('w-[4px] -mr-[2px]');
    expect(inspector).not.toContain('data-inspector-hub');
    expect(inspector).not.toContain('data-inspector-hub-item');
    expect(inspector).not.toContain('ShortcutPill');
    expect(inspector).not.toContain('data-inspector-panel-menu');
    expect(inspector).not.toContain('<Plus');
    expect(inspector).toContain('isPinnedInspectorTab');
    expect(inspector).toContain('data-inspector-tab-pinned');
    expect(inspector).toContain('{!pinned && (');
    expect(inspector).toContain('bg-page');
    expect(inspector).toContain('min-w-[360px]');
    expect(inspector).toContain('data-inspector-panel');
    expect(inspector).toContain('role="tablist"');
    expect(inspector).toContain('role="tab"');
    expect(inspector).toContain('data-inspector-tab-strip');
    expect(inspector).toContain('data-inspector-tab-id={tab.id}');
    expect(inspector).toContain('data-inspector-tab-close');
    expect(inspector).toContain('draggable={!pinned}');
    expect(inspector).toContain('onAuxClick');
    expect(inspector).toContain("event.key === 'ArrowLeft'");
    expect(inspector).toContain("event.key === 'ArrowRight'");
    expect(inspector).toContain("event.key === 'Home'");
    expect(inspector).toContain("event.key === 'End'");
    expect(inspector).toContain('scrollIntoView');
    expect(inspector).toContain('onOpenTab(kind)');
    expect(inspector).toContain('data-changed-files-section');
    expect(inspector).toContain("labelKey: 'review'");
    expect(inspector).toContain('<ReviewPanel');
    expect(inspector).toContain('data-review-section');
    expect(inspector).toContain('data-plan-section');
    expect(inspector).toContain('data-plan-points-title');
    expect(inspector).toContain('<InspectorPlanPanel');
    expect(inspector).toContain('workflowProposal={workflowProposal}');
    expect(inspector).toContain('viewedProposalMarkdown={activeTab.viewedProposalMarkdown}');
    expect(inspector).toContain('viewedProposalSessionId={activeTab.viewedProposalSessionId}');
    expect(inspector).toContain('activeSessionId={activeSessionId}');
    expect(inspector).not.toContain('<PlanPoints points={workflowPlan?.plan || []} />');
    expect(inspector).not.toContain('ScreenPreviewCard');
    expect(inspector).not.toContain('Routines');
    expect(inspector).not.toContain('UsageQuotaCard');
    expect(inspector).not.toContain('TokenUsageBar');
    expect(inspector).not.toContain('aria-expanded={filesExpanded}');
    expect(inspector).not.toContain('filesExpanded');
    expect(points).toContain('data-plan-points-empty');
    expect(points).toContain('noPlanPointsYet');
    expect(points).toContain('Points created by update_plan will appear here.');
    expect(points).toContain("import TaskRows, { type TaskRow }");
    expect(points).toContain('<TaskRows');
    expect(points).toContain('variant="List"');
    expect(points).toContain('rows={rows}');
    expect(points).toContain("point.status === 'completed'");
    expect(points).toContain("point.status === 'in_progress'");
    expect(points).toContain("? 'done'");
    expect(points).toContain("? 'running'");
    expect(points).toContain(": 'pending'");
    expect(points).toContain("amount: ''");
    expect(points).toContain('maxVisibleRows');
    expect(points).toContain('expandable={false}');
    expect(taskRows).toContain('maxVisibleRows?: number');
    expect(taskRows).toContain('maxHeight: `${maxVisibleRows * 44}px`');
    expect(taskRows).toContain('"shrink-0 self-stretch overflow-hidden');
    expect(taskRows).toContain('disabled={!expandable}');
    expect(taskRows).toContain('{expandable ? (');
    expect(points).not.toContain('ResizeObserver');
    expect(points).not.toContain('transition-all');
    expect(points).not.toContain('flex flex-col gap-0.5');
    expect(points).not.toContain('min-h-9');
    expect(points).not.toContain('CircleCheckBig');
    expect(points).not.toContain('CircleDot');
    expect(reviewPanel).toContain('data-component="session-review-v2"');
    expect(reviewPanel).toContain('data-review-panel');
    expect(reviewSidebar).toContain('data-slot="session-review-v2-sidebar"');
    expect(reviewSidebar).toContain('filterFiles');
    expect(reviewEmpty).toContain('data-slot="session-review-v2-empty-no-git"');
    expect(reviewEmpty).toContain('data-review-init-git');
    expect(inspector).toContain('data-copy-plan-button');
    expect(inspector).toContain('handleCopyPlan');
    expect(inspector).not.toContain('hover:bg-slate-50');
    expect(app).toContain('inspectorTabsReducer');
    expect(app).toContain('tabs={inspectorTabsState.tabs}');
    expect(app).toContain('activeTabId={inspectorTabsState.activeTabId}');
    expect(app).toContain('captureInspectorTabs');
  });

  it('uses authoritative workflow plan snapshots and reconciles plan entries', () => {
    const hook = source('desktop/src/hooks/useMetisServer.ts');
    expect(hook).toContain('workflowPlan?: WorkflowPlanState');
    expect(hook).toContain('setWorkflowPlan(state.workflowPlan)');
    expect(hook).toContain("type === 'entry_appended'");
    expect(hook).toContain("['workflow_plan', 'workflow_plan_reset']");
    expect(hook).toContain('workflowPlan,');
  });

  it('wires plan state into the right sidebar and provides runtime capture', () => {
    const app = source('desktop/src/App.tsx');
    const main = source('desktop/main.cjs');
    const panel = source('desktop/src/components/inspector/InspectorPlanPanel.tsx');
    expect(app).toContain('workflowPlan={displayedWorkflowPlan}');
    expect(app).toContain('workflowProposal={displayedProposal}');
    expect(app).toContain('openInspectorPlan');
    expect(app).toContain('viewedProposalSessionId');
    expect(app).toContain("type: 'clearPlanViews'");
    expect(app).toContain('activeSessionId={activeAgentId || messagesSessionId || null}');
    expect(app).toContain('toolParts={displayedToolParts}');
    expect(app).toContain('workspacePath={displayedWorkspacePath}');
    expect(app).toContain('const displayedWorkspacePath = capturePlanPoints || captureInspectorTabs ? PLAN_POINTS_CAPTURE_WORKSPACE : activeProject?.path');
    expect(app).not.toContain('fileChanges={displayedFileChanges}');
    expect(app).not.toContain('routines={routines}');
    expect(app).toContain('isOAuth={isOAuthModel}');
    expect(app).toContain('totalCost={aggregateCost}');
    expect(app).toContain('quota5h={quota5h}');
    expect(source('desktop/src/components/inspector/Inspector.tsx')).not.toContain('isOAuth=');
    expect(source('desktop/src/components/inspector/Inspector.tsx')).not.toContain('UsageQuotaCard');
    expect(panel).toContain('data-inspector-plan-markdown');
    expect(panel).toContain('data-inspector-plan-todos');
    expect(panel).not.toContain('reactUiPlanTodos');
    expect(panel).toContain('data-plan-process');
    expect(panel).toContain('<PlanPoints points={points} compactEmpty maxVisibleRows={3} />');
    expect(panel).not.toContain('max-h-[min(42vh,320px)]');
    expect(panel.indexOf('data-inspector-plan-todos')).toBeLessThan(panel.indexOf('data-inspector-plan-markdown'));
    expect(panel).toContain('data-inspector-plan-todos-pin');
    expect(panel).toContain('data-inspector-plan-todos-fade');
    expect(panel).toContain('data-inspector-plan-body');
    expect(panel).toContain('contentScrollRef');
    expect(panel).toContain('bg-page');
    expect(panel).toContain('bg-gradient-to-b from-page');
    expect(panel).not.toContain('className="relative min-w-0 rounded-card');
    expect(panel).not.toContain('rounded-[10px] px-3.5 py-3');
    expect(source('desktop/src/components/inspector/Inspector.tsx')).toContain('contentScrollRef={contentScrollRef}');
    expect(source('desktop/src/components/inspector/Inspector.tsx')).toContain('overflow-hidden px-3.5 pb-3.5 pt-2');
    expect(main).toContain('METIS_DESKTOP_CAPTURE_PLAN_POINTS');
    expect(main).toContain('METIS_DESKTOP_CAPTURE_PLAN_POINTS_EMPTY');
    expect(main).toContain('METIS_DESKTOP_CAPTURE_INSPECTOR_TABS');
    expect(main).toContain('[capture:inspector-tabs]');
    expect(main).toContain('[capture:plan-points]');
    expect(main).toContain('titleAlignedWithIcon');
    expect(main).toContain('changedFilePaths');
    expect(main).toContain('lightBackground');
    expect(main).toContain('darkBackground');
    expect(main).toContain('capsuleToDivider');
    expect(main).toContain('dividerToTodos');
    expect(main).toContain('todosMatchesCapsuleGap');
    expect(main).toContain('todosTitleRemoved');
    expect(main).toContain('completedTaskCount');
    expect(main).toContain('hasRowDividers');
    expect(main).toContain('taskRowsRadius');
    expect(main).toContain('taskRowHeights');
    expect(main).toContain('rowsExpandable');
    expect(main).toContain('scrollsBeyondThree');
    expect(main).toContain('fourthClipped');
    expect(main).toContain('maxVisibleRows');
  });
});
