import type { WorkProgressPhase } from './work-progress';

export type WorkProgressCopyState = WorkProgressPhase | 'idle' | 'task-received';

export const WORK_PROGRESS_LABELS: Record<WorkProgressCopyState, readonly string[]> = {
  idle: [
    'Response complete',
    'All set',
    'Ready when you are',
    'Standing by',
    'Task wrapped up',
    'Ready for the next step',
    'Here if you need me',
    'Finished and standing by',
    'All done for now',
    'Ready for what is next',
    'Everything is set',
    'Waiting for your cue',
    'All clear and ready',
    'Task completed',
    'Standing by for instructions',
    'Ready whenever you are',
    'Good to go',
    'Completed and standing by',
    'At your service',
    'Ready for your next request',
    'Done and ready',
  ],
  'task-received': [
    'Task received…',
    'Getting started…',
    'On it…',
    'Starting the task…',
    'Setting things in motion…',
    'Taking on the request…',
    'Lining up the work…',
    'Kicking off the task…',
    'Picking up the request…',
    'Preparing the workspace…',
    'Getting things rolling…',
    'Initializing the task…',
    'Beginning the process…',
    'Stepping into the task…',
    'Getting right to it…',
    'Queueing up the work…',
    'Setting up the next step…',
    'Opening the request…',
    'Starting right away…',
    'Beginning the work…',
    'Jumping in…',
  ],
  thinking: [
    'Analyzing the request…',
    'Thinking through the details…',
    'Mapping the next steps…',
    'Working through the context…',
    'Forming an approach…',
    'Exploring the possibilities…',
    'Evaluating the solution…',
    'Connecting the pieces…',
    'Reasoning through the problem…',
    'Weighing the options…',
    'Breaking down the goal…',
    'Structuring the plan…',
    'Considering the constraints…',
    'Mapping out the strategy…',
    'Clarifying the requirements…',
    'Thinking ahead…',
    'Synthesizing the details…',
    'Charting the course…',
    'Formulating a plan…',
    'Piecing the solution together…',
    'Assessing the approach…',
  ],
  waiting: [
    'Waiting for the next signal…',
    'Standing by for input…',
    'Waiting on a response…',
    'Pausing for the next step…',
    'Holding here for now…',
    'Waiting for confirmation…',
    'Listening for updates…',
    'Standing by for the next event…',
    'Pausing for user guidance…',
    'Holding until ready…',
    'Waiting for external signals…',
    'Awaiting your direction…',
    'Pausing briefly…',
    'Standing by for clarification…',
    'Holding for instructions…',
    'Waiting for background tasks…',
    'Standing by patiently…',
    'Awaiting the next prompt…',
    'Holding for the green light…',
    'Waiting for input to proceed…',
    'Standing by for review…',
  ],
  reading: [
    'Reading the source material…',
    'Reviewing the details…',
    'Gathering context…',
    'Inspecting the relevant files…',
    'Taking in the latest information…',
    'Reading through the code…',
    'Examining project contents…',
    'Parsing the documentation…',
    'Reviewing the codebase…',
    'Loading relevant context…',
    'Studying the existing logic…',
    'Absorbing the requirements…',
    'Scanning the definitions…',
    'Looking over the file structure…',
    'Checking referenced sources…',
    'Reading project context…',
    'Inspecting the declarations…',
    'Reviewing project standards…',
    'Gathering technical details…',
    'Reading through specifications…',
    'Examining the file details…',
  ],
  searching: [
    'Searching for the right path…',
    'Looking through the codebase…',
    'Finding the relevant pieces…',
    'Tracing the source…',
    'Exploring possible matches…',
    'Searching for references…',
    'Locating key symbols…',
    'Scanning for relevant files…',
    'Tracking down dependencies…',
    'Finding where things are defined…',
    'Searching across the project…',
    'Hunting down usages…',
    'Discovering related components…',
    'Navigating the codebase…',
    'Looking for matches…',
    'Pinpointing the exact location…',
    'Searching for definitions…',
    'Tracing call paths…',
    'Exploring relevant patterns…',
    'Looking across the codebase…',
    'Searching for related code…',
  ],
  executing: [
    'Putting the changes in place…',
    'Working on the implementation…',
    'Applying the update…',
    'Making the requested changes…',
    'Moving the task forward…',
    'Running the operation…',
    'Executing the step…',
    'Carrying out the edits…',
    'Applying code modifications…',
    'Executing commands…',
    'Writing out the changes…',
    'Implementing the solution…',
    'Running the required tasks…',
    'Applying updates cleanly…',
    'Refactoring the code…',
    'Processing the operations…',
    'Applying target adjustments…',
    'Working through the actions…',
    'Executing the plan…',
    'Putting the edits together…',
    'Performing the updates…',
  ],
  issue: [
    'Recovering from an issue…',
    'Adjusting the approach…',
    'Working around a problem…',
    'Resolving an unexpected result…',
    'Getting things back on track…',
    'Handling the edge case…',
    'Troubleshooting the failure…',
    'Retrying with adjustments…',
    'Investigating the setback…',
    'Refining the strategy…',
    'Correcting the course…',
    'Resolving the blocker…',
    'Finding a workaround…',
    'Stepping through the error…',
    'Fixing the discrepancy…',
    'Adapting to the obstacle…',
    'Recovering smoothly…',
    'Patching the unexpected result…',
    'Reworking the approach…',
    'Straightening things out…',
    'Overcoming the hiccup…',
  ],
  drafting: [
    'Drafting the response…',
    'Writing up the result…',
    'Turning the work into an answer…',
    'Preparing the response…',
    'Shaping the final message…',
    'Organizing the findings…',
    'Crafting the explanation…',
    'Putting thoughts into words…',
    'Formulating the response…',
    'Structuring the summary…',
    'Compiling the output…',
    'Synthesizing the conclusion…',
    'Writing a clear explanation…',
    'Drafting key takeaways…',
    'Putting the answer together…',
    'Refining the wording…',
    'Summarizing the progress…',
    'Drafting the final answer…',
    'Formatting the result…',
    'Structuring the findings…',
    'Writing up the outcome…',
  ],
  coordinating: [
    'Coordinating the work…',
    'Bringing the pieces together…',
    'Syncing with the team…',
    'Delegating the next step…',
    'Keeping the work moving…',
    'Aligning parallel tasks…',
    'Managing subagent progress…',
    'Synthesizing team results…',
    'Orchestrating the steps…',
    'Checking in with agents…',
    'Syncing ongoing efforts…',
    'Harmonizing the work…',
    'Distributing subtasks…',
    'Consolidating agent outputs…',
    'Balancing active workflows…',
    'Coordinating sub-processes…',
    'Keeping everything in sync…',
    'Reviewing parallel streams…',
    'Connecting agent outputs…',
    'Orchestrating the workflow…',
    'Syncing project streams…',
  ],
  checking: [
    'Checking the latest result…',
    'Verifying the details…',
    'Reviewing the outcome…',
    'Making sure everything lines up…',
    'Running a final check…',
    'Testing the changes…',
    'Inspecting the output…',
    'Validating the result…',
    'Double checking the logic…',
    'Confirming correctness…',
    'Verifying test passes…',
    'Reviewing the diff…',
    'Auditing the updates…',
    'Ensuring clean execution…',
    'Checking edge cases…',
    'Running verification tests…',
    'Confirming the integrity…',
    'Reviewing final details…',
    'Verifying expectations…',
    'Inspecting test results…',
    'Checking code quality…',
  ],
  finalizing: [
    'Finalizing the response…',
    'Finishing the last details…',
    'Wrapping up the result…',
    'Preparing the final answer…',
    'Completing the response…',
    'Putting on the finishing touches…',
    'Cleaning up before completion…',
    'Wrapping things up…',
    'Polishing the output…',
    'Bringing the task to a close…',
    'Sealing the final updates…',
    'Getting everything ready for you…',
    'Completing final handoff…',
    'Tying up loose ends…',
    'Preparing the delivery…',
    'Putting final touches in place…',
    'Completing the final review…',
    'Finishing the task cleanly…',
    'Wrapping up neatly…',
    'Getting the final answer ready…',
    'Closing out the task…',
  ],
};

export function pickWorkProgressLabel(
  state: WorkProgressCopyState,
  random: () => number = Math.random,
  previous?: string,
): string {
  const choices = WORK_PROGRESS_LABELS[state];
  const randomValue = Math.max(0, Math.min(0.999999, random()));
  const index = Math.floor(randomValue * choices.length);
  const choice = choices[index];
  return choice === previous && choices.length > 1
    ? choices[(index + 1) % choices.length]
    : choice;
}

