// Core session management

export { type Args, parseArgs } from "./cli/args.ts";

// Config paths
export {
	CONFIG_DIR_NAME,
	getAgentDir,
	getDocsPath,
	getExamplesPath,
	getPackageDir,
	getReadmePath,
	getUserAgentsDir,
	VERSION,
} from "./config.ts";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	type QueuedSessionMessage,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
export {
	MemoryCoordinator,
	type MemoryCandidate,
	type MemoryCategory,
	MEMORY_CATEGORIES,
	CATEGORY_DISPLAY_TITLES,
	normalizeCategory,
	categoryToKind,
	type MemoryCoordinatorOptions,
	type MemoryExtractionResult,
	type MemoryKind,
	type MemoryRecordStatus,
	type MemoryRecordSummary,
	type MemoryScope,
	type MemorySearchOptions,
	type MemorySettings,
	type MemoryState,
	type SessionMemoryCheckpoint,
	resolveMemoryProjectIdentity,
} from "./core/memory-coordinator.ts";
export { validateAskUserRequest, validateAskUserResponse, type AskUserAnswer, type AskUserHandler, type AskUserOption, type AskUserQuestion, type AskUserRequest, type AskUserResponse } from "./core/ask-user.ts";
export { extractProposedPlan, getLatestWorkflowProposal, resolveWorkflowPlan, resolveWorkflowProposal, type WorkflowPlanPhase, type WorkflowPlanState, type WorkflowPlanStep, type WorkflowProposalState } from "./core/workflow-runtime.ts";
export {
	PerformanceRuntime,
	getPerformanceGovernanceRoot,
	getPerformanceRunDirectory,
	missionPointer,
	summarizePerformanceRun,
	validatePerformanceSpawn,
	type PerformanceConcurrency,
	type PerformanceAttendance,
	type PerformanceEffortCapability,
	type PerformanceAgentLease,
	type PerformanceGate,
	type PerformanceGateReport,
	type PerformanceRunState,
	type PerformanceRunSummary,
	type PerformanceRunStatus,
	type PerformanceSpawnDecision,
	type PerformanceSpawnRequest,
	type PerformanceStartInvocation,
} from "./core/performance-runtime.ts";
export {
	parsePerformanceRoadmapItems,
	performanceItemGatePolicy,
	PERFORMANCE_ROADMAP_CATEGORIES,
	PERFORMANCE_ROADMAP_TAGS,
	PERFORMANCE_ROADMAP_TIERS,
	type PerformanceItemGatePolicy,
	type PerformanceRoadmapCategory,
	type PerformanceRoadmapItem,
	type PerformanceRoadmapTag,
	type PerformanceRoadmapTier,
} from "./core/performance-roadmap.ts";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	type AuthStatus,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeStepEvent,
	BeforeStepEventResult,
	BeforeTransportRequestEvent,
	BeforeTransportRequestResult,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	EntryRenderer,
	EntryRenderOptions,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionInfoChangedEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolCapabilities,
	ToolEffect,
	ToolDefinition,
	ToolExecutionMode,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export { convertToLlm } from "./core/messages.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export {
	type ModelScopeDiagnostic,
	type ResolveCliModelResult,
	type ResolveModelScopeResult,
	resolveCliModel,
	resolveModelScopeWithDiagnostics,
	type ScopedModel,
} from "./core/model-resolver.ts";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./core/resource-loader.ts";
// Multi-Agent core (Bundle 1 & Bundle 3)
export {
	AgentRegistry,
	type AgentDefinition,
	type AgentDiscoveryResult,
	type AgentFrontmatter,
	AgentFrontmatterSchema,
	type AgentScope,
	BUILTIN_AGENTS,
	BUILTIN_COORDINATOR,
	BUILTIN_IMPLEMENTER,
	BUILTIN_PLANNER,
	BUILTIN_REVIEWER,
	BUILTIN_VERIFIER,
	formatAgentsForPrompt,
	type GlobalDefaultConfig,
	loadAgents,
	loadAgentsFromDir,
	MAX_AGENT_DESCRIPTION_LENGTH,
	MAX_AGENT_NAME_LENGTH,
	type ParentAgentRuntimeConfig,
	parseAgentDefinition,
	resolveAgentConfig,
	type ResolveAgentConfigOptions,
	type ResolvedAgentConfig,
	validateAgentDescription,
	validateAgentName,
} from "./core/agent-definition.ts";
export {
	SpawnGuard,
	type SpawnGuardConfig,
	type SpawnValidationResult,
	type SpawnErrorCode,
	type ChildAgentStatus,
	type ChildAgentState,
	type CanSpawnOptions,
	DEFAULT_MAX_SPAWN_DEPTH,
	DEFAULT_MAX_CHILDREN_PER_AGENT,
	DEFAULT_MAX_TOTAL_CHILDREN,
	DEFAULT_MAX_CONCURRENT_AGENTS,
	DEFAULT_AGENT_TIMEOUT_MS,
	computeTaskHash,
	getGlobalSpawnGuard,
	setGlobalSpawnGuard,
} from "./core/spawn-guard.ts";
export {
	type IsolatedWorkspace,
	type CreateIsolatedWorkspaceOptions,
	createIsolatedWorkspace,
	cleanupIsolatedWorkspace,
	isGitRepository,
} from "./core/worktree.ts";
export {
	DANGEROUS_ENV_VARS,
	filterChildEnvironment,
	maskSecretValue,
	sanitizeSensitiveString,
	sanitizeTraceData,
} from "./core/env-sanitizer.ts";
export {
	TraceCollector,
	type TraceContext,
	type AgentTokenStats,
	type TraceSummaryPayload,
	getGlobalTraceCollector,
	setGlobalTraceCollector,
} from "./core/trace-collector.ts";
export {
	type CollaborationMode,
	type StepSnapshot,
	type WorkflowCheckpoint,
	type WorkflowToolErrorKind,
	WorkflowToolDispatcher,
	WorkflowToolError,
	WorkflowRuntime,
} from "./core/workflow-runtime.ts";
export {
	type InstructionBlock,
	type InstructionChannel,
	type InstructionSourceSummary,
	type InstructionStack,
	type InstructionTrust,
	buildInstructionStack,
	compileInstructionStack,
	instructionStackHash,
} from "./core/system-prompt.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLogTool,
	createSpawnAgentTool,
	createWebSearchTool,
	createWebFetchTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createVideoTool,
	createWriteTool,
	type PromptTemplate,
} from "./core/sdk.ts";
export {
	type BranchSummaryEntry,
	type CollaborationModeChangeEntry,
	buildContextEntries,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type SessionTreeNode,
	sessionEntryToContextMessages,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	type CompactionSettings,
	type DefaultProjectTrust,
	type ImageSettings,
	type PackageSource,
	type RetrySettings,
	SettingsManager,
	type SettingsManagerCreateOptions,
	type WorkingMemorySettings,
} from "./core/settings-manager.ts";
export {
	RESOLVED_UI_LANGUAGES,
	type ResolvedUiLanguage,
	SUPPORTED_UI_LANGUAGES,
	type UiLanguage,
} from "./core/ui-language.ts";
// Skills
export {
	BUILTIN_SKILLS,
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
export { type EditDiffResult, generateDiffString, generateUnifiedPatch } from "./core/tools/edit-diff.ts";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createSpawnAgentToolDefinition,
	spawnAgentSchema,
	type SpawnAgentToolInput,
	type SpawnAgentToolOptions,
	type SpawnAgentRuntimeContext,
	type ChildAgentResultPayload,
	createListAgentsToolDefinition,
	listAgentsSchema,
	type ListAgentsToolInput,
	createWaitAgentToolDefinition,
	waitAgentSchema,
	type WaitAgentToolInput,
	createKillAgentToolDefinition,
	killAgentSchema,
	type KillAgentToolInput,
	createMessageAgentToolDefinition,
	messageAgentSchema,
	type MessageAgentToolInput,
	type AgentManagementToolOptions,
	createWebSearchToolDefinition,
	createWebFetchToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLsToolDefinition,
	createReadToolDefinition,
	createQueryMemoryDbTool,
	createQueryMemoryDbToolDefinition,
	createVideoToolDefinition,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type QueryMemoryDbToolInput,
	type QueryMemoryDbToolOptions,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type VideoAction,
	type VideoCrop,
	type VideoMetadata,
	type VideoOperations,
	type VideoToolDetails,
	type VideoToolInput,
	type VideoToolOptions,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export {
	hasTrustRequiringProjectResources,
	type ProjectTrustDecision,
	ProjectTrustStore,
	type ProjectTrustStoreEntry,
	type ProjectTrustUpdate,
} from "./core/trust-manager.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type ModelInfo,
	type PrintModeOptions,
	RpcClient,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcExtensionUIRequest,
	type RpcExtensionUIResponse,
	type RpcResponse,
	type RpcSessionState,
	type ServerModeOptions,
	runPrintMode,
	runRpcMode,
	runServerMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	LanguageSelectorComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";

